### ISSUE TITLE
What are the advantages of DeepDan compared to CLIP and BLIP?

### ISSUE THREAD

**Issue by TomLucidor** [Jibaku789/sd-webui-deepdanbooru-object-recognition#3]
sorry for asking but other than having a stronger classifier
1. Would generated heatmaps be useful for masking rather than bounding boxes?
2. Could this identify the causes for "burn" in high CFG or high step images?

https://github.com/pharmapsychotic/clip-interrogator-ext

**Comment by Jibaku789** [comment]
> What are the advantages of DeepDan compared to CLIP and BLIP?

In essence, CLIP and BLIP works different than DeepDanbooru
CLIP/BLIP are to generate sequences of text from images and follow the seq2seq style.
https://arxiv.org/abs/2103.00020v1

Deepdanbooru is just a classification model where the output are the tag by itself like any other CNN Multilabel Classification / Resnet.

> Would generated heatmaps be useful for masking rather than bounding boxes?

heatmaps and the actual python libraries have two limitations to make masking
1.- The libraries like seaborn or matplotlib not generate only the canvas and it includes the labels and legend in the output image
2.- My algorithm of identification assumes overlaps in the pixels, if i would like to generate a perfect b/w heatmap, the parameter should not overlap between the kernel size and the step size.

> Could this identify the causes for "burn" in high CFG or high step images?

No, this extension is not able to identify burn in high CFG
